name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    label: 'enhancement'
    label: 'feature'
  - title: 'Fixes'
    label: 'fix'
    label: 'bug'
  - title: 'ETC'
    label: 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Uncategorized
  $CHANGES
